server:
  port: 0

spring:
  application:
    name: health-analyzer # Nombre para Eureka
  datasource:
    url: jdbc:postgresql://localhost:26257/medical_db?sslmode=disable
    username: root
    password: # tu_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDBDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}