server:
  port: 8000

spring:
  application:
    name: API-GATEWAY # Nombre para Eureka

  cloud:
    gateway:
      # --- INICIO DE CAMBIOS DE PROPIEDADES ---
      # Propiedades de Gateway que antes estaban directamente bajo 'gateway'
      # ahora van bajo 'server.webflux' para seguir la nueva estructura.
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            # Ruta para PatientDataCollector
            - id: patient-data-collector-route
              uri: lb://PATIENT-DATA-COLLECTOR
              predicates:
                - Path=/conjunta/2p/collector/**
              filters:
                - StripPrefix=3

            # Ruta para CareNotifier
            - id: care-notifier-route
              uri: lb://CARE-NOTIFIER
              predicates:
                - Path=/conjunta/2p/notifier/**
              filters:
                - StripPrefix=3

            # Ruta para HealthAnalyzer
            - id: health-analyzer-route
              uri: lb://HEALTH-ANALYZER
              predicates:
                - Path=/conjunta/2p/analyzer/**
              filters:
                - StripPrefix=3
      # --- FIN DE CAMBIOS DE PROPIEDADES ---

      # 'actuator' se movió un nivel arriba, directamente bajo 'gateway'
      actuator:
        verbose:
          enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      base-path: /actuator
      # Esta es la única configuración necesaria para exponer el endpoint del gateway.
      exposure:
        include: gateway,health,info