server:
    port: 0

spring:
    application:
        name: PATIENT-DATA-COLLECTOR
    datasource:
        url: jdbc:postgresql://localhost:26257/db_patient_data?user=root&password=
        username: root
        password:
        driver-class-name: org.postgresql.Driver

    resilience-datasource:
        url: jdbc:postgresql://localhost:5432/resilience_db_collector # Base de datos local. Asegúrate de que exista.
        username: postgres # ¡CAMBIAR! Tu usuario de PostgreSQL local.
        password: alex # ¡CAMBIAR! Tu contraseña de PostgreSQL local.
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    rabbitmq:
        host: localhost
        port: 5672
        username: admin
        password: admin

eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${random.value}

management:
    endpoints:
        web:
            exposure:
                include: health,info,gateway